name: Workflow with Validation and Manual Approval

on: [push]

jobs:
  workflow:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/checkout@v4

      - id: validation
        run: |
          # Add your validation commands here
          title="some title text"
          body="some body text"
          echo "some_title_text=$title" >> $GITHUB_OUTPUT
          echo "some_body_text=$body" >> $GITHUB_OUTPUT
          echo "OUTPUT key: some_title_text; value: $title"
          echo "OUTPUT key: some_body_text; value: $body"

      - uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: ${{ github.actor }}
          minimum-approvals: 1
          issue-title: ${{ steps.validation.outputs.some_title_text }}
          issue-body: ${{ steps.validation.outputs.some_body_text }}
          exclude-workflow-initiator-as-approver: false
          additional-approved-words: 'continue, ok'
          additional-denied-words: 'stop, cancel'

      - name: Run execution
        run: |
          # Add your execution commands here
          echo "Executing the workflow after approval."
